name: Build and Deploy Strapi Docker Image

on:
  push:
    tags:
      - "v*"       # Déclenche sur tous les tags commençant par "v"
      - "v*-beta"  # Déclenche sur tous les tags contenant "beta"
  workflow_dispatch: # Permet le déclenchement manuel depuis l'interface GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configuration de Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Étape 3 : Construction de l'image Docker
      - name: Build Docker image
        run: |
          docker build -t dreamsite-admin:${{ github.ref_name }} ./back

      # Étape 4 : (Optionnel) Push de l'image vers un registre Docker
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag dreamsite-admin:${{ github.ref_name }} kevinad/dreamsite-admin:${{ github.ref_name }}
          docker push kevinad/dreamsite-admin:${{ github.ref_name }}
